import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { getUser } from "./services/auth/actions";

import "./globals.css";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Inability Code",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const user = await getUser()

  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="container gap-10 !h-screen ">
            <Header  user={user}/>
            {children}
            </div>
           
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
