import type { Metadata } from "next";
import { ThemeProvider } from "@/components/ui/theme-provider";

import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Inability Code",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="container gap-10">
            <Header />
            {children}
            </div>
           
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
